### ISSUE TITLE
Issue on Windows 10 (x64)

### ISSUE THREAD

**Issue by faceuckadoss** [xupwup/LoLPatcher#19]
I´ve been using the patcher for quite some time right now and I just updated to Windows 10 for free, but the patcher wont work anymore, Ive tried reinstalling JRE, Im using jre 8u91 for 64 bits, Im pretty much sure the update is the reason Im having this problem because I opened the patcher right before the update and it was working fine, whenever I click the patcher executable it shows the mouse working (like the rolling circle icon), but then it does nothing, tried redownloading the LoLPatcher thing from your page but didnt work either, please help me solve this mess I havent been able to play League since, I really like your patcher because of its download speed since I have really poor connection.
Thanks for reading, hope you can come up with a solution. :)

**Comment by xupwup** [comment]
Does PATCHLOG.txt (in the same directory as my patcher) exist? If so, please post it. Otherwise, my only guess is to update your graphics drivers.

If the aforementioned file does not exist, could you make a screenshot of the program in its "does nothing" state?

**Comment by faceuckadoss** [comment]
Yes the PATCHLOG.txt exists, but updating the graphics drivers seemed to get the job done, its now working, thank you so much xupwup, loving your launcher, keep up the good work. 

Oh, one question, why did you eliminate news from the launcher?

**Comment by xupwup** [comment]
> Oh, one question, why did you eliminate news from the launcher?

Riot's old patcher got it's news items from a different place. Riot's new patcher was a complete visual overhaul, and downloads its news assets differently to accomodate for the new format. My patcher got news items the same way as Riot's old patcher, but since that one was replaced two years ago, you can imagine that Riot isn't keeping the old news format updated properly. The result was that my patcher would display outdated news, and would sometimes not even work (https://github.com/xupwup/LoLPatcher/issues/12), because Riot's server malfunctioned. That meant that I could either update to the new news format, or I could replace the whole thing by something that required less maintenance.

**Comment by faceuckadoss** [comment]
I see, are you planning on updating to the new news format any time soon? I like the goo thing on the patcher dont get me wrong, but it just doesnt fit its purpose, again, keep up the good work!

**Comment by xupwup** [comment]
No, I'm not intending to update anything. I'm only doing the minimal amount of work to keep the patcher going, and adding a proper news feed would require more maintenance. I don't have as much spare time as I used to.
